// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM9MQ6Bo0xqEOwwe8kndvwQYlwyPUVx24',
    appId: '1:159470745726:web:d1ce79909ff9a42bd8402f',
    messagingSenderId: '159470745726',
    projectId: 'homefix-b6610',
    authDomain: 'homefix-b6610.firebaseapp.com',
    storageBucket: 'homefix-b6610.firebasestorage.app',
    measurementId: 'G-NXEMF1SGZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcWAY5epIsj8f-Fo7UTGm4IEcYZLohD0',
    appId: '1:159470745726:android:919d308843065c02d8402f',
    messagingSenderId: '159470745726',
    projectId: 'homefix-b6610',
    storageBucket: 'homefix-b6610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLqyYJwuG1zufSmy8MDcgryTHyDFaWCYM',
    appId: '1:159470745726:ios:6ba9bad4fb4304bbd8402f',
    messagingSenderId: '159470745726',
    projectId: 'homefix-b6610',
    storageBucket: 'homefix-b6610.firebasestorage.app',
    iosBundleId: 'com.example.hmfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM9MQ6Bo0xqEOwwe8kndvwQYlwyPUVx24',
    appId: '1:159470745726:web:e67026967d8598b6d8402f',
    messagingSenderId: '159470745726',
    projectId: 'homefix-b6610',
    authDomain: 'homefix-b6610.firebaseapp.com',
    storageBucket: 'homefix-b6610.firebasestorage.app',
    measurementId: 'G-YXQKH31QLK',
  );
}
